# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'itunesClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for itunesClone

  pod 'RxSwift'
  pod 'RxCocoa'


  target 'itunesCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'itunesCloneUITests' do
    # Pods for testing
  end

end
